#!/usr/bin/env bash
set -euo pipefail

ROOT="platform"

dirs=(
  "$ROOT/.github/workflows"
  "$ROOT/.github/ISSUE_TEMPLATE"

  "$ROOT/proto/aic/inference/v1"
  "$ROOT/proto/aic/context/v1"
  "$ROOT/proto/aic/safety/v1"
  "$ROOT/proto/aic/tools/v1"
  "$ROOT/proto/aic/common/v1"
  "$ROOT/proto/gen/rust"
  "$ROOT/proto/gen/python"

  "$ROOT/services/api-gateway/src/routes"
  "$ROOT/services/api-gateway/src/middleware"
  "$ROOT/services/api-gateway/src/auth"
  "$ROOT/services/api-gateway/src/upstream"
  "$ROOT/services/api-gateway/src/streaming"
  "$ROOT/services/api-gateway/tests/integration"
  "$ROOT/services/api-gateway/tests/common"

  "$ROOT/services/context-service/src/routers"
  "$ROOT/services/context-service/src/services"
  "$ROOT/services/context-service/src/clients"
  "$ROOT/services/context-service/src/models"
  "$ROOT/services/context-service/src/utils"
  "$ROOT/services/context-service/tests/unit"
  "$ROOT/services/context-service/tests/integration"

  "$ROOT/services/safety-service/src/routers"
  "$ROOT/services/safety-service/src/classifiers"
  "$ROOT/services/safety-service/src/policy"
  "$ROOT/services/safety-service/src/models"
  "$ROOT/services/safety-service/src/utils"
  "$ROOT/services/safety-service/tests/unit"
  "$ROOT/services/safety-service/tests/fixtures"

  "$ROOT/services/memory-service/src/routers"
  "$ROOT/services/memory-service/src/services"
  "$ROOT/services/memory-service/src/models"
  "$ROOT/services/memory-service/src/db/migrations/versions"
  "$ROOT/services/memory-service/src/utils"
  "$ROOT/services/memory-service/tests/unit"
  "$ROOT/services/memory-service/tests/integration"

  "$ROOT/services/tool-orchestrator/src/routes"
  "$ROOT/services/tool-orchestrator/src/tools"
  "$ROOT/services/tool-orchestrator/src/mcp"
  "$ROOT/services/tool-orchestrator/tests/unit"
  "$ROOT/services/tool-orchestrator/tests/integration"

  "$ROOT/services/mcp-proxy/src/routes"
  "$ROOT/services/mcp-proxy/src/proxy"
  "$ROOT/services/mcp-proxy/src/oauth"
  "$ROOT/services/mcp-proxy/tests/integration"

  "$ROOT/services/conversation-store/src/routes"
  "$ROOT/services/conversation-store/src/db"
  "$ROOT/services/conversation-store/src/models"
  "$ROOT/services/conversation-store/migrations"
  "$ROOT/services/conversation-store/tests/integration"

  "$ROOT/services/operator-service/src/routers"
  "$ROOT/services/operator-service/src/models"
  "$ROOT/services/operator-service/src/db"
  "$ROOT/services/operator-service/tests"

  "$ROOT/libs/rust/aic-auth/src"
  "$ROOT/libs/rust/aic-tracing/src"
  "$ROOT/libs/rust/aic-config/src"
  "$ROOT/libs/rust/aic-errors/src"

  "$ROOT/libs/python/aic-internal-auth/src/aic_internal_auth"
  "$ROOT/libs/python/aic-internal-logging/src/aic_internal_logging"
  "$ROOT/libs/python/aic-internal-tracing/src/aic_internal_tracing"

  "$ROOT/infra/terraform/environments/staging"
  "$ROOT/infra/terraform/environments/production"
  "$ROOT/infra/terraform/modules/eks"
  "$ROOT/infra/terraform/modules/rds"
  "$ROOT/infra/terraform/modules/elasticache"
  "$ROOT/infra/terraform/modules/networking"

  "$ROOT/infra/kubernetes/base/api-gateway"
  "$ROOT/infra/kubernetes/base/context-service"
  "$ROOT/infra/kubernetes/base/safety-service"
  "$ROOT/infra/kubernetes/base/memory-service"
  "$ROOT/infra/kubernetes/base/tool-orchestrator"
  "$ROOT/infra/kubernetes/base/mcp-proxy"
  "$ROOT/infra/kubernetes/base/shared"
  "$ROOT/infra/kubernetes/overlays/staging"
  "$ROOT/infra/kubernetes/overlays/production"

  "$ROOT/infra/helm/claude-platform/templates"

  "$ROOT/monitoring/grafana/dashboards"
  "$ROOT/monitoring/grafana/datasources"
  "$ROOT/monitoring/prometheus/alerts"
  "$ROOT/monitoring/runbooks"

  "$ROOT/scripts"

  "$ROOT/docs/architecture"
  "$ROOT/docs/runbooks"
  "$ROOT/docs/adr"
  "$ROOT/docs/onboarding"
)

files=(
  "$ROOT/.github/workflows/ci-rust.yml"
  "$ROOT/.github/workflows/ci-python.yml"
  "$ROOT/.github/workflows/integration-tests.yml"
  "$ROOT/.github/workflows/e2e-tests.yml"
  "$ROOT/.github/workflows/docker-build.yml"
  "$ROOT/.github/workflows/deploy-staging.yml"
  "$ROOT/.github/workflows/deploy-production.yml"
  "$ROOT/.github/workflows/security-scan.yml"
  "$ROOT/.github/CODEOWNERS"
  "$ROOT/.github/pull_request_template.md"
  "$ROOT/.github/ISSUE_TEMPLATE/bug_report.md"
  "$ROOT/.github/ISSUE_TEMPLATE/incident.md"
  "$ROOT/.github/ISSUE_TEMPLATE/feature_request.md"
  "$ROOT/.github/SECURITY.md"

  "$ROOT/.gitignore"
  "$ROOT/.gitattributes"
  "$ROOT/.editorconfig"
  "$ROOT/.env.example"
  "$ROOT/.env.staging.example"
  "$ROOT/.env.production.example"
  "$ROOT/.pre-commit-config.yaml"
  "$ROOT/.python-version"
  "$ROOT/README.md"
  "$ROOT/CONTRIBUTING.md"
  "$ROOT/PROPRIETARY"
  "$ROOT/Cargo.toml"
  "$ROOT/Cargo.lock"
  "$ROOT/pyproject.toml"
  "$ROOT/uv.lock"
  "$ROOT/Makefile"
  "$ROOT/justfile"

  "$ROOT/proto/buf.yaml"
  "$ROOT/proto/buf.gen.yaml"
  "$ROOT/proto/aic/inference/v1/messages.proto"
  "$ROOT/proto/aic/inference/v1/streaming.proto"
  "$ROOT/proto/aic/inference/v1/models.proto"
  "$ROOT/proto/aic/context/v1/context.proto"
  "$ROOT/proto/aic/context/v1/memory.proto"
  "$ROOT/proto/aic/safety/v1/classify.proto"
  "$ROOT/proto/aic/safety/v1/policy.proto"
  "$ROOT/proto/aic/tools/v1/tool.proto"
  "$ROOT/proto/aic/tools/v1/mcp.proto"
  "$ROOT/proto/aic/common/v1/types.proto"
  "$ROOT/proto/aic/common/v1/errors.proto"

  "$ROOT/services/api-gateway/Cargo.toml"
  "$ROOT/services/api-gateway/README.md"
  "$ROOT/services/api-gateway/.env.example"
  "$ROOT/services/api-gateway/Dockerfile"
  "$ROOT/services/api-gateway/src/main.rs"
  "$ROOT/services/api-gateway/src/lib.rs"
  "$ROOT/services/api-gateway/src/config.rs"
  "$ROOT/services/api-gateway/src/app.rs"
  "$ROOT/services/api-gateway/src/routes/mod.rs"
  "$ROOT/services/api-gateway/src/routes/messages.rs"
  "$ROOT/services/api-gateway/src/routes/models.rs"
  "$ROOT/services/api-gateway/src/routes/health.rs"
  "$ROOT/services/api-gateway/src/routes/admin.rs"
  "$ROOT/services/api-gateway/src/middleware/mod.rs"
  "$ROOT/services/api-gateway/src/middleware/auth.rs"
  "$ROOT/services/api-gateway/src/middleware/rate_limit.rs"
  "$ROOT/services/api-gateway/src/middleware/quota.rs"
  "$ROOT/services/api-gateway/src/middleware/logging.rs"
  "$ROOT/services/api-gateway/src/middleware/tracing.rs"
  "$ROOT/services/api-gateway/src/middleware/cors.rs"
  "$ROOT/services/api-gateway/src/auth/mod.rs"
  "$ROOT/services/api-gateway/src/auth/api_key.rs"
  "$ROOT/services/api-gateway/src/auth/jwt.rs"
  "$ROOT/services/api-gateway/src/auth/workspace.rs"
  "$ROOT/services/api-gateway/src/upstream/mod.rs"
  "$ROOT/services/api-gateway/src/upstream/context_client.rs"
  "$ROOT/services/api-gateway/src/upstream/safety_client.rs"
  "$ROOT/services/api-gateway/src/upstream/inference_client.rs"
  "$ROOT/services/api-gateway/src/upstream/tool_client.rs"
  "$ROOT/services/api-gateway/src/streaming/mod.rs"
  "$ROOT/services/api-gateway/src/streaming/sse.rs"
  "$ROOT/services/api-gateway/src/streaming/transformer.rs"
  "$ROOT/services/api-gateway/src/errors.rs"
  "$ROOT/services/api-gateway/tests/integration/test_messages.rs"
  "$ROOT/services/api-gateway/tests/integration/test_auth.rs"
  "$ROOT/services/api-gateway/tests/integration/test_rate_limit.rs"
  "$ROOT/services/api-gateway/tests/common/mod.rs"

  "$ROOT/services/context-service/pyproject.toml"
  "$ROOT/services/context-service/README.md"
  "$ROOT/services/context-service/.env.example"
  "$ROOT/services/context-service/Dockerfile"
  "$ROOT/services/context-service/src/__init__.py"
  "$ROOT/services/context-service/src/main.py"
  "$ROOT/services/context-service/src/config.py"
  "$ROOT/services/context-service/src/app.py"
  "$ROOT/services/context-service/src/routers/__init__.py"
  "$ROOT/services/context-service/src/routers/context.py"
  "$ROOT/services/context-service/src/routers/health.py"
  "$ROOT/services/context-service/src/services/__init__.py"
  "$ROOT/services/context-service/src/services/assembler.py"
  "$ROOT/services/context-service/src/services/memory_injector.py"
  "$ROOT/services/context-service/src/services/tool_injector.py"
  "$ROOT/services/context-service/src/services/system_prompt.py"
  "$ROOT/services/context-service/src/services/truncator.py"
  "$ROOT/services/context-service/src/services/compressor.py"
  "$ROOT/services/context-service/src/clients/__init__.py"
  "$ROOT/services/context-service/src/clients/memory_client.py"
  "$ROOT/services/context-service/src/clients/operator_client.py"
  "$ROOT/services/context-service/src/models/__init__.py"
  "$ROOT/services/context-service/src/models/context.py"
  "$ROOT/services/context-service/src/models/message.py"
  "$ROOT/services/context-service/src/utils/__init__.py"
  "$ROOT/services/context-service/src/utils/token_counter.py"
  "$ROOT/services/context-service/src/utils/logging.py"
  "$ROOT/services/context-service/tests/conftest.py"
  "$ROOT/services/context-service/tests/unit/test_assembler.py"
  "$ROOT/services/context-service/tests/unit/test_truncator.py"
  "$ROOT/services/context-service/tests/unit/test_system_prompt.py"
  "$ROOT/services/context-service/tests/integration/test_context_api.py"

  "$ROOT/services/safety-service/pyproject.toml"
  "$ROOT/services/safety-service/README.md"
  "$ROOT/services/safety-service/.env.example"
  "$ROOT/services/safety-service/Dockerfile"
  "$ROOT/services/safety-service/src/__init__.py"
  "$ROOT/services/safety-service/src/main.py"
  "$ROOT/services/safety-service/src/config.py"
  "$ROOT/services/safety-service/src/app.py"
  "$ROOT/services/safety-service/src/routers/__init__.py"
  "$ROOT/services/safety-service/src/routers/classify.py"
  "$ROOT/services/safety-service/src/routers/policy.py"
  "$ROOT/services/safety-service/src/routers/health.py"
  "$ROOT/services/safety-service/src/classifiers/__init__.py"
  "$ROOT/services/safety-service/src/classifiers/harm_classifier.py"
  "$ROOT/services/safety-service/src/classifiers/topic_classifier.py"
  "$ROOT/services/safety-service/src/classifiers/child_safety.py"
  "$ROOT/services/safety-service/src/classifiers/weapons.py"
  "$ROOT/services/safety-service/src/classifiers/pii_detector.py"
  "$ROOT/services/safety-service/src/policy/__init__.py"
  "$ROOT/services/safety-service/src/policy/engine.py"
  "$ROOT/services/safety-service/src/policy/operator_policy.py"
  "$ROOT/services/safety-service/src/policy/constitution.py"
  "$ROOT/services/safety-service/src/models/__init__.py"
  "$ROOT/services/safety-service/src/models/model_loader.py"
  "$ROOT/services/safety-service/src/models/inference.py"
  "$ROOT/services/safety-service/src/utils/__init__.py"
  "$ROOT/services/safety-service/src/utils/logging.py"
  "$ROOT/services/safety-service/tests/conftest.py"
  "$ROOT/services/safety-service/tests/unit/test_harm_classifier.py"
  "$ROOT/services/safety-service/tests/unit/test_policy_engine.py"
  "$ROOT/services/safety-service/tests/fixtures/safe_samples.json"
  "$ROOT/services/safety-service/tests/fixtures/.gitignore"

  "$ROOT/services/memory-service/pyproject.toml"
  "$ROOT/services/memory-service/README.md"
  "$ROOT/services/memory-service/.env.example"
  "$ROOT/services/memory-service/Dockerfile"
  "$ROOT/services/memory-service/src/__init__.py"
  "$ROOT/services/memory-service/src/main.py"
  "$ROOT/services/memory-service/src/config.py"
  "$ROOT/services/memory-service/src/app.py"
  "$ROOT/services/memory-service/src/routers/__init__.py"
  "$ROOT/services/memory-service/src/routers/memory.py"
  "$ROOT/services/memory-service/src/routers/search.py"
  "$ROOT/services/memory-service/src/routers/health.py"
  "$ROOT/services/memory-service/src/services/__init__.py"
  "$ROOT/services/memory-service/src/services/memory_store.py"
  "$ROOT/services/memory-service/src/services/embedder.py"
  "$ROOT/services/memory-service/src/services/extractor.py"
  "$ROOT/services/memory-service/src/services/ranker.py"
  "$ROOT/services/memory-service/src/services/privacy.py"
  "$ROOT/services/memory-service/src/models/__init__.py"
  "$ROOT/services/memory-service/src/models/memory.py"
  "$ROOT/services/memory-service/src/models/schemas.py"
  "$ROOT/services/memory-service/src/db/__init__.py"
  "$ROOT/services/memory-service/src/db/session.py"
  "$ROOT/services/memory-service/src/db/migrations/env.py"
  "$ROOT/services/memory-service/src/db/migrations/versions/0001_init.py"
  "$ROOT/services/memory-service/src/db/migrations/versions/0002_add_pgvector.py"
  "$ROOT/services/memory-service/src/db/migrations/versions/0003_add_user_edits.py"
  "$ROOT/services/memory-service/src/utils/__init__.py"
  "$ROOT/services/memory-service/src/utils/logging.py"
  "$ROOT/services/memory-service/tests/conftest.py"
  "$ROOT/services/memory-service/tests/unit/test_extractor.py"
  "$ROOT/services/memory-service/tests/unit/test_ranker.py"
  "$ROOT/services/memory-service/tests/unit/test_privacy.py"
  "$ROOT/services/memory-service/tests/integration/test_memory_api.py"

  "$ROOT/services/tool-orchestrator/Cargo.toml"
  "$ROOT/services/tool-orchestrator/README.md"
  "$ROOT/services/tool-orchestrator/.env.example"
  "$ROOT/services/tool-orchestrator/Dockerfile"
  "$ROOT/services/tool-orchestrator/src/main.rs"
  "$ROOT/services/tool-orchestrator/src/lib.rs"
  "$ROOT/services/tool-orchestrator/src/config.rs"
  "$ROOT/services/tool-orchestrator/src/app.rs"
  "$ROOT/services/tool-orchestrator/src/routes/mod.rs"
  "$ROOT/services/tool-orchestrator/src/routes/tools.rs"
  "$ROOT/services/tool-orchestrator/src/routes/health.rs"
  "$ROOT/services/tool-orchestrator/src/tools/mod.rs"
  "$ROOT/services/tool-orchestrator/src/tools/registry.rs"
  "$ROOT/services/tool-orchestrator/src/tools/executor.rs"
  "$ROOT/services/tool-orchestrator/src/tools/sandbox.rs"
  "$ROOT/services/tool-orchestrator/src/tools/web_search.rs"
  "$ROOT/services/tool-orchestrator/src/tools/web_fetch.rs"
  "$ROOT/services/tool-orchestrator/src/tools/computer_use.rs"
  "$ROOT/services/tool-orchestrator/src/tools/image_search.rs"
  "$ROOT/services/tool-orchestrator/src/tools/artifact.rs"
  "$ROOT/services/tool-orchestrator/src/mcp/mod.rs"
  "$ROOT/services/tool-orchestrator/src/mcp/client.rs"
  "$ROOT/services/tool-orchestrator/src/errors.rs"
  "$ROOT/services/tool-orchestrator/tests/unit/test_registry.rs"
  "$ROOT/services/tool-orchestrator/tests/unit/test_executor.rs"
  "$ROOT/services/tool-orchestrator/tests/integration/test_tool_api.rs"

  "$ROOT/services/mcp-proxy/Cargo.toml"
  "$ROOT/services/mcp-proxy/README.md"
  "$ROOT/services/mcp-proxy/.env.example"
  "$ROOT/services/mcp-proxy/Dockerfile"
  "$ROOT/services/mcp-proxy/src/main.rs"
  "$ROOT/services/mcp-proxy/src/lib.rs"
  "$ROOT/services/mcp-proxy/src/config.rs"
  "$ROOT/services/mcp-proxy/src/app.rs"
  "$ROOT/services/mcp-proxy/src/routes/mod.rs"
  "$ROOT/services/mcp-proxy/src/routes/proxy.rs"
  "$ROOT/services/mcp-proxy/src/routes/connectors.rs"
  "$ROOT/services/mcp-proxy/src/routes/health.rs"
  "$ROOT/services/mcp-proxy/src/proxy/mod.rs"
  "$ROOT/services/mcp-proxy/src/proxy/sse_client.rs"
  "$ROOT/services/mcp-proxy/src/proxy/auth_injector.rs"
  "$ROOT/services/mcp-proxy/src/proxy/tool_filter.rs"
  "$ROOT/services/mcp-proxy/src/proxy/rate_limiter.rs"
  "$ROOT/services/mcp-proxy/src/oauth/mod.rs"
  "$ROOT/services/mcp-proxy/src/oauth/token_store.rs"
  "$ROOT/services/mcp-proxy/src/oauth/refresh.rs"
  "$ROOT/services/mcp-proxy/src/errors.rs"
  "$ROOT/services/mcp-proxy/tests/integration/test_proxy.rs"

  "$ROOT/services/conversation-store/Cargo.toml"
  "$ROOT/services/conversation-store/README.md"
  "$ROOT/services/conversation-store/.env.example"
  "$ROOT/services/conversation-store/Dockerfile"
  "$ROOT/services/conversation-store/src/main.rs"
  "$ROOT/services/conversation-store/src/config.rs"
  "$ROOT/services/conversation-store/src/app.rs"
  "$ROOT/services/conversation-store/src/routes/mod.rs"
  "$ROOT/services/conversation-store/src/routes/conversations.rs"
  "$ROOT/services/conversation-store/src/routes/messages.rs"
  "$ROOT/services/conversation-store/src/routes/health.rs"
  "$ROOT/services/conversation-store/src/db/mod.rs"
  "$ROOT/services/conversation-store/src/db/pool.rs"
  "$ROOT/services/conversation-store/src/db/queries.rs"
  "$ROOT/services/conversation-store/src/models/mod.rs"
  "$ROOT/services/conversation-store/src/models/conversation.rs"
  "$ROOT/services/conversation-store/src/models/message.rs"
  "$ROOT/services/conversation-store/migrations/0001_init.sql"
  "$ROOT/services/conversation-store/migrations/0002_add_metadata.sql"
  "$ROOT/services/conversation-store/migrations/0003_add_projects.sql"
  "$ROOT/services/conversation-store/tests/integration/test_conversations.rs"

  "$ROOT/services/operator-service/pyproject.toml"
  "$ROOT/services/operator-service/README.md"
  "$ROOT/services/operator-service/.env.example"
  "$ROOT/services/operator-service/Dockerfile"
  "$ROOT/services/operator-service/src/__init__.py"
  "$ROOT/services/operator-service/src/main.py"
  "$ROOT/services/operator-service/src/config.py"
  "$ROOT/services/operator-service/src/app.py"
  "$ROOT/services/operator-service/src/routers/__init__.py"
  "$ROOT/services/operator-service/src/routers/operators.py"
  "$ROOT/services/operator-service/src/routers/policies.py"
  "$ROOT/services/operator-service/src/routers/usage.py"
  "$ROOT/services/operator-service/src/routers/health.py"
  "$ROOT/services/operator-service/src/models/__init__.py"
  "$ROOT/services/operator-service/src/models/operator.py"
  "$ROOT/services/operator-service/src/models/policy.py"
  "$ROOT/services/operator-service/src/db/__init__.py"
  "$ROOT/services/operator-service/src/db/session.py"
  "$ROOT/services/operator-service/tests/conftest.py"

  "$ROOT/libs/rust/aic-auth/Cargo.toml"
  "$ROOT/libs/rust/aic-auth/src/lib.rs"
  "$ROOT/libs/rust/aic-auth/src/api_key.rs"
  "$ROOT/libs/rust/aic-auth/src/jwt.rs"
  "$ROOT/libs/rust/aic-tracing/Cargo.toml"
  "$ROOT/libs/rust/aic-tracing/src/lib.rs"
  "$ROOT/libs/rust/aic-config/Cargo.toml"
  "$ROOT/libs/rust/aic-config/src/lib.rs"
  "$ROOT/libs/rust/aic-errors/Cargo.toml"
  "$ROOT/libs/rust/aic-errors/src/lib.rs"

  "$ROOT/libs/python/aic-internal-auth/pyproject.toml"
  "$ROOT/libs/python/aic-internal-auth/src/aic_internal_auth/__init__.py"
  "$ROOT/libs/python/aic-internal-auth/src/aic_internal_auth/client.py"
  "$ROOT/libs/python/aic-internal-logging/pyproject.toml"
  "$ROOT/libs/python/aic-internal-logging/src/aic_internal_logging/__init__.py"
  "$ROOT/libs/python/aic-internal-logging/src/aic_internal_logging/logger.py"
  "$ROOT/libs/python/aic-internal-tracing/pyproject.toml"
  "$ROOT/libs/python/aic-internal-tracing/src/aic_internal_tracing/__init__.py"
  "$ROOT/libs/python/aic-internal-tracing/src/aic_internal_tracing/otel.py"

  "$ROOT/infra/terraform/environments/staging/main.tf"
  "$ROOT/infra/terraform/environments/staging/variables.tf"
  "$ROOT/infra/terraform/environments/staging/terraform.tfvars.example"
  "$ROOT/infra/terraform/environments/production/main.tf"
  "$ROOT/infra/terraform/environments/production/variables.tf"
  "$ROOT/infra/terraform/environments/production/terraform.tfvars.example"

  "$ROOT/infra/kubernetes/base/api-gateway/deployment.yaml"
  "$ROOT/infra/kubernetes/base/api-gateway/service.yaml"
  "$ROOT/infra/kubernetes/base/api-gateway/hpa.yaml"
  "$ROOT/infra/kubernetes/base/api-gateway/pdb.yaml"
  "$ROOT/infra/kubernetes/base/context-service/deployment.yaml"
  "$ROOT/infra/kubernetes/base/context-service/service.yaml"
  "$ROOT/infra/kubernetes/base/safety-service/deployment.yaml"
  "$ROOT/infra/kubernetes/base/safety-service/service.yaml"
  "$ROOT/infra/kubernetes/base/memory-service/deployment.yaml"
  "$ROOT/infra/kubernetes/base/memory-service/service.yaml"
  "$ROOT/infra/kubernetes/base/tool-orchestrator/deployment.yaml"
  "$ROOT/infra/kubernetes/base/tool-orchestrator/service.yaml"
  "$ROOT/infra/kubernetes/base/mcp-proxy/deployment.yaml"
  "$ROOT/infra/kubernetes/base/mcp-proxy/service.yaml"
  "$ROOT/infra/kubernetes/base/shared/namespace.yaml"
  "$ROOT/infra/kubernetes/base/shared/network-policies.yaml"
  "$ROOT/infra/kubernetes/base/shared/rbac.yaml"
  "$ROOT/infra/kubernetes/overlays/staging/kustomization.yaml"
  "$ROOT/infra/kubernetes/overlays/production/kustomization.yaml"
  "$ROOT/infra/kubernetes/kustomization.yaml"

  "$ROOT/infra/helm/claude-platform/Chart.yaml"
  "$ROOT/infra/helm/claude-platform/values.yaml"
  "$ROOT/infra/helm/claude-platform/values.staging.yaml"
  "$ROOT/infra/helm/claude-platform/values.production.yaml"

  "$ROOT/monitoring/grafana/dashboards/api-gateway.json"
  "$ROOT/monitoring/grafana/dashboards/latency-p99.json"
  "$ROOT/monitoring/grafana/dashboards/safety-classifier.json"
  "$ROOT/monitoring/grafana/dashboards/inference-throughput.json"
  "$ROOT/monitoring/grafana/datasources/prometheus.yaml"
  "$ROOT/monitoring/prometheus/alerts/latency.yaml"
  "$ROOT/monitoring/prometheus/alerts/error-rate.yaml"
  "$ROOT/monitoring/prometheus/alerts/safety.yaml"
  "$ROOT/monitoring/prometheus/recording_rules.yaml"
  "$ROOT/monitoring/runbooks/high-latency.md"
  "$ROOT/monitoring/runbooks/safety-classifier-failure.md"
  "$ROOT/monitoring/runbooks/rate-limit-spike.md"

  "$ROOT/scripts/bootstrap.sh"
  "$ROOT/scripts/build-all.sh"
  "$ROOT/scripts/test-all.sh"
  "$ROOT/scripts/migrate-all.sh"
  "$ROOT/scripts/generate-proto.sh"

  "$ROOT/docs/architecture/overview.md"
  "$ROOT/docs/architecture/request-lifecycle.md"
  "$ROOT/docs/architecture/context-assembly.md"
  "$ROOT/docs/architecture/safety-pipeline.md"
  "$ROOT/docs/architecture/memory-system.md"
  "$ROOT/docs/adr/0001-rust-for-gateway.md"
  "$ROOT/docs/adr/0002-pgvector-for-memory.md"
  "$ROOT/docs/adr/0003-grpc-inter-service.md"
  "$ROOT/docs/onboarding/platform-team.md"
  "$ROOT/docs/onboarding/local-dev.md"
)

for dir in "${dirs[@]}"; do
  mkdir -p "$dir"
done

for file in "${files[@]}"; do
  mkdir -p "$(dirname "$file")"
  : > "$file"
done

chmod +x \
  "$ROOT/scripts/bootstrap.sh" \
  "$ROOT/scripts/build-all.sh" \
  "$ROOT/scripts/test-all.sh" \
  "$ROOT/scripts/migrate-all.sh" \
  "$ROOT/scripts/generate-proto.sh"

echo "Generated placeholder scaffold at: $ROOT"